project:
  type: website
  output-dir: docs
website:
  title: "LetsGetIt"
  navbar:
    left:
      - href: index.qmd
      - about.qmd
      - model.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

